// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/kingjxu/ddbaby/dal"
)

func main() {
	logger := NewLogger()
	hlog.SetLogger(logger)
	dal.Init()
	h := server.Default()

	register(h)
	h.Spin()
}
