package health_evaluate

import (
	"context"
	"github.com/kingjxu/ddbaby/dal/mysql"
)

// Code generated by sql2gorm. DO NOT EDIT.

// 健康评估问题表
type HealthEvaluationQuestions struct {
	ID           uint64 `gorm:"column:id;primary_key;AUTO_INCREMENT"` // 自增id
	QuestionType string `gorm:"column:question_type;NOT NULL"`        // 问题所属类别
	Content      string `gorm:"column:content"`                       // 问题
	Options      string `gorm:"column:options"`                       // 问题选项
}

func (*HealthEvaluationQuestions) TableName() string {
	return "health_evaluation_questions"
}

func GetQuestionsByType(ctx context.Context, questionType string) ([]*HealthEvaluationQuestions, error) {
	var questions []*HealthEvaluationQuestions
	err := mysql.GetDB(ctx).Where("question_type = ?", questionType).Find(&questions).Error
	return questions, err
}
