// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

// GetMatchList .
// @router /world_cup/match_list [GET]
func GetMatchList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.GetMatchListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := NewGetMatchListHandler(&req).Handle(ctx)
	logrus.WithContext(ctx).Infof("GetMatchList resp:%v", util.ToJSON(resp))
	c.JSON(consts.StatusOK, resp)
}

type GetMatchListHandler struct {
	req *ddbaby.GetMatchListReq

	resp *ddbaby.GetMatchListResp
}

func NewGetMatchListHandler(req *ddbaby.GetMatchListReq) *GetMatchListHandler {
	return &GetMatchListHandler{
		req:  req,
		resp: &ddbaby.GetMatchListResp{},
	}
}

func (h *GetMatchListHandler) check() error {
	return nil
}

func (h *GetMatchListHandler) Handle(ctx context.Context) (*ddbaby.GetMatchListResp, error) {
	logrus.WithContext(ctx).Infof("[GetMatchListHandler] req:%+v", util.ToJSON(h.req))
	if err := h.check(); err != nil {
		logrus.WithContext(ctx).Errorf("[GetMatchListHandler] check err:%v", err)
		return h.newResp(ctx, -1, "param err"), nil
	}
	h.resp = h.newResp(ctx, 0, "success")
	h.resp.MatchList = matchList
	return h.resp, nil
}

func (h *GetMatchListHandler) newResp(ctx context.Context, code int32, msg string) *ddbaby.GetMatchListResp {
	resp := &ddbaby.GetMatchListResp{
		BaseResp: &ddbaby.BaseResp{
			StatusMessage: msg,
			StatusCode:    code,
		},
	}
	return resp
}

var matchList = map[string][]*ddbaby.MatchInfo{
	"20260701": {{
		HostTeam:  util.Ptr("美国"),
		HostIcon:  util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/america.png"),
		GuestTeam: util.Ptr("日本"),
		GuestIcon: util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/japan.png"),
		BetType: map[string][]*ddbaby.OddsItem{
			"胜负": {
				{
					Text: util.Ptr("胜"),
					Odds: util.Ptr(1.41),
				},
				{
					Text: util.Ptr("平"),
					Odds: util.Ptr(2.5),
				},
				{
					Text: util.Ptr("负"),
					Odds: util.Ptr(3.5),
				},
			},
			"比分": {
				{
					Text: util.Ptr("1:0"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("2:0"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2:1"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("3:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("3:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("4:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("4:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("5:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("5:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("胜其它"),
					Odds: util.Ptr(8.5),
				},
				{
					Text: util.Ptr("0:0"),
					Odds: util.Ptr(1.0),
				},
				{
					Text: util.Ptr("1:1"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("2:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("3:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("平其它"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:1"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("0:2"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("0:3"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:3"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:4"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:4"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:5"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:5"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:5"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("负其它"),
					Odds: util.Ptr(8.5),
				},
			},
			"总进球": {
				{
					Text: util.Ptr("0球"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("1球"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2球"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3球"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4球"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("6球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("7球"),
					Odds: util.Ptr(8.0),
				},
			},
			"半全场": {
				{
					Text: util.Ptr("胜胜"),
					Odds: util.Ptr(2.0),
				},
				{
					Text: util.Ptr("胜平"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("胜负"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("平胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平负"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负负"),
					Odds: util.Ptr(4.0),
				},
			},
		},
	}, {
		HostTeam:  util.Ptr("澳大利亚"),
		HostIcon:  util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/australia.png"),
		GuestTeam: util.Ptr("克罗地亚"),
		GuestIcon: util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/croatia.png"),
		BetType: map[string][]*ddbaby.OddsItem{
			"胜负": {
				{
					Text: util.Ptr("胜"),
					Odds: util.Ptr(1.41),
				},
				{
					Text: util.Ptr("平"),
					Odds: util.Ptr(2.5),
				},
				{
					Text: util.Ptr("负"),
					Odds: util.Ptr(3.5),
				},
			},
			"比分": {
				{
					Text: util.Ptr("1:0"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("2:0"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2:1"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("3:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("3:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("4:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("4:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("5:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("5:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("胜其它"),
					Odds: util.Ptr(8.5),
				},
				{
					Text: util.Ptr("0:0"),
					Odds: util.Ptr(1.0),
				},
				{
					Text: util.Ptr("1:1"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("2:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("3:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("平其它"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:1"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("0:2"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("0:3"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:3"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:4"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:4"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:5"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:5"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:5"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("负其它"),
					Odds: util.Ptr(8.5),
				},
			},
			"总进球": {
				{
					Text: util.Ptr("0球"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("1球"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2球"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3球"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4球"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("6球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("7球"),
					Odds: util.Ptr(8.0),
				},
			},
			"半全场": {
				{
					Text: util.Ptr("胜胜"),
					Odds: util.Ptr(2.0),
				},
				{
					Text: util.Ptr("胜平"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("胜负"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("平胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平负"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负负"),
					Odds: util.Ptr(4.0),
				},
			},
		},
	}},
	"20260702": {{
		HostTeam:  util.Ptr("美国"),
		HostIcon:  util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/america.png"),
		GuestTeam: util.Ptr("澳大利亚"),
		GuestIcon: util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/australia.png"),
		BetType: map[string][]*ddbaby.OddsItem{
			"胜负": {
				{
					Text: util.Ptr("胜"),
					Odds: util.Ptr(1.41),
				},
				{
					Text: util.Ptr("平"),
					Odds: util.Ptr(2.5),
				},
				{
					Text: util.Ptr("负"),
					Odds: util.Ptr(3.5),
				},
			},
			"比分": {
				{
					Text: util.Ptr("1:0"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("2:0"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2:1"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("3:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("3:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("4:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("4:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("5:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("5:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("胜其它"),
					Odds: util.Ptr(8.5),
				},
				{
					Text: util.Ptr("0:0"),
					Odds: util.Ptr(1.0),
				},
				{
					Text: util.Ptr("1:1"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("2:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("3:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("平其它"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:1"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("0:2"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("0:3"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:3"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:4"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:4"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:5"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:5"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:5"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("负其它"),
					Odds: util.Ptr(8.5),
				},
			},
			"总进球": {
				{
					Text: util.Ptr("0球"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("1球"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2球"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3球"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4球"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("6球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("7球"),
					Odds: util.Ptr(8.0),
				},
			},
			"半全场": {
				{
					Text: util.Ptr("胜胜"),
					Odds: util.Ptr(2.0),
				},
				{
					Text: util.Ptr("胜平"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("胜负"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("平胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平负"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负负"),
					Odds: util.Ptr(4.0),
				},
			},
		},
	}, {
		HostTeam:  util.Ptr("日本"),
		HostIcon:  util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/japan.png"),
		GuestTeam: util.Ptr("克罗地亚"),
		GuestIcon: util.Ptr("https://lf3-static.bytednsdoc.com/obj/eden-cn/qeeh7upqbe/croatia.png"),
		BetType: map[string][]*ddbaby.OddsItem{
			"胜负": {
				{
					Text: util.Ptr("胜"),
					Odds: util.Ptr(1.41),
				},
				{
					Text: util.Ptr("平"),
					Odds: util.Ptr(2.5),
				},
				{
					Text: util.Ptr("负"),
					Odds: util.Ptr(3.5),
				},
			},
			"比分": {
				{
					Text: util.Ptr("1:0"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("2:0"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2:1"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("3:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("3:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("4:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("4:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("5:0"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("5:1"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("胜其它"),
					Odds: util.Ptr(8.5),
				},
				{
					Text: util.Ptr("0:0"),
					Odds: util.Ptr(1.0),
				},
				{
					Text: util.Ptr("1:1"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("2:2"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("3:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("平其它"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:1"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("0:2"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("0:3"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:3"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:3"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:4"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:4"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:4"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("0:5"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("1:5"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("2:5"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("负其它"),
					Odds: util.Ptr(8.5),
				},
			},
			"总进球": {
				{
					Text: util.Ptr("0球"),
					Odds: util.Ptr(5.0),
				},
				{
					Text: util.Ptr("1球"),
					Odds: util.Ptr(5.70),
				},
				{
					Text: util.Ptr("2球"),
					Odds: util.Ptr(6.0),
				},
				{
					Text: util.Ptr("3球"),
					Odds: util.Ptr(6.5),
				},
				{
					Text: util.Ptr("4球"),
					Odds: util.Ptr(7.0),
				},
				{
					Text: util.Ptr("5球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("6球"),
					Odds: util.Ptr(8.0),
				},
				{
					Text: util.Ptr("7球"),
					Odds: util.Ptr(8.0),
				},
			},
			"半全场": {
				{
					Text: util.Ptr("胜胜"),
					Odds: util.Ptr(2.0),
				},
				{
					Text: util.Ptr("胜平"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("胜负"),
					Odds: util.Ptr(3.0),
				},
				{
					Text: util.Ptr("平胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("平负"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负胜"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负平"),
					Odds: util.Ptr(4.0),
				},
				{
					Text: util.Ptr("负负"),
					Odds: util.Ptr(4.0),
				},
			},
		},
	}},
}
