// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

// HealthEvaluateQuestions .
// @router /health/questions [GET]
func HealthEvaluateQuestions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.HealthEvaluateQuestionsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ddbaby.HealthEvaluateQuestionsResp)

	c.JSON(consts.StatusOK, resp)
}
