// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"
	"github.com/kingjxu/ddbaby/service"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

// TaLuoPredict .
// @router /lyxz/taluo_predict [GET]
func TaLuoPredict(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.TaLuoPredictReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := NewTaLuoPredictHandler(&req).Handle(ctx)

	c.JSON(consts.StatusOK, resp)
}

type TaLuoPredictHandler struct {
	req     *ddbaby.TaLuoPredictReq
	Explain string
}

func NewTaLuoPredictHandler(req *ddbaby.TaLuoPredictReq) *TaLuoPredictHandler {
	return &TaLuoPredictHandler{
		req: req,
	}
}

func (h *TaLuoPredictHandler) check() error {
	if h.req.GetQuery() == "" {
		return errors.New("query is empty")
	}
	return nil
}

func (h *TaLuoPredictHandler) Handle(ctx context.Context) (*ddbaby.TaLuoPredictResp, error) {
	logrus.WithContext(ctx).Infof("[TaLuoPredictHandler] req:%v", util.ToJSON(h.req))
	if err := h.check(); err != nil {
		logrus.WithContext(ctx).Errorf("[TaLuoPredictHandler] check err:%v", err)
		return h.newResp(ctx, -1, "param err"), nil
	}
	content, err := service.TaLuoPredict(ctx, h.req.GetQuery())
	if err != nil {
		logrus.WithContext(ctx).Errorf("[TaLuoPredictHandler] ta luo predict err:%v", err)
		return h.newResp(ctx, -2, "predict err"), nil
	}
	h.Explain = content
	return h.newResp(ctx, 0, ""), nil
}

func (h *TaLuoPredictHandler) newResp(ctx context.Context, code int32, msg string) *ddbaby.TaLuoPredictResp {
	resp := &ddbaby.TaLuoPredictResp{
		BaseResp: &ddbaby.BaseResp{
			StatusMessage: msg,
			StatusCode:    code,
		},
	}
	resp.Explain = &h.Explain

	return resp
}
