// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"
	"fmt"
	"github.com/kingjxu/ddbaby/ark"
	_const "github.com/kingjxu/ddbaby/const"
	"github.com/kingjxu/ddbaby/service"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

// TexasPokerDecision .
// @router /lyxz/gto_decision [POST]
func TexasPokerDecision(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.TexasPokerDecisionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, _ := NewTexasPokerDecisionHandler(&req).Handle(ctx)
	logrus.WithContext(ctx).Infof("[TexasPokerDecision] resp:%v", util.ToJSON(resp))
	c.JSON(consts.StatusOK, resp)
}

type TexasPokerDecisionHandler struct {
	req     *ddbaby.TexasPokerDecisionReq
	Action  string
	BetSize int32
}

func NewTexasPokerDecisionHandler(req *ddbaby.TexasPokerDecisionReq) *TexasPokerDecisionHandler {
	return &TexasPokerDecisionHandler{
		req: req,
	}
}

func (h *TexasPokerDecisionHandler) check() error {
	if len(h.req.GetImages()) == 0 {
		return errors.New("images is empty")
	}
	if h.req.GetImageTime() > 0 && h.req.GetImageTime() < time.Now().Unix()-4 {
		return errors.New("image too old")
	}
	return nil
}

func (h *TexasPokerDecisionHandler) Handle(ctx context.Context) (*ddbaby.TexasPokerDecisionResp, error) {
	logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] imagesLen:%v, imageTime:%v", len(h.req.GetImages()), h.req.GetImageTime())
	if err := h.check(); err != nil {
		logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] check err:%v", err)
		return h.newResp(ctx, "param err"), nil
	}
	images := h.req.GetImages()
	imageType := _const.ImageTypeUrl
	if len(images[0]) > 512 && (h.req.GetImageType() == _const.ImageTypeUrl || h.req.GetImageType() == "") { // 图片的二进制数据
		imageUrls, err := service.UploadImagesV2(ctx, images)
		if err != nil {
			logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] service.UploadImage err:%v", err)
			return h.newResp(ctx, "upload image err"), nil
		}
		images = imageUrls
	} else if len(images[0]) > 512 && (h.req.GetImageType() == _const.ImageTypeFileID) { // 图片的fileID
		imageIDs, err := service.UploadImages(ctx, images)
		if err != nil {
			logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] service.UploadImage err:%v", err)
			return h.newResp(ctx, "upload image err"), nil
		}
		images = imageIDs
		imageType = _const.ImageTypeFileID
	}
	decision := util.UnmarshalString[TexasPokerDecisionV2](ark.TexasPokerDecision(ctx, images[0]))
	logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] imageType:%v, decision:%v", imageType, util.ToJSON(decision))
	return h.newResp(ctx, getFinalDecision(decision)), nil
}

func getFinalDecision(decision TexasPokerDecisionV2) string {
	if strings.ToLower(decision.Action) == "fold" {
		return "弃牌"
	} else if strings.ToLower(decision.Action) == "check" {
		return "过牌"
	} else if strings.ToLower(decision.Action) == "bet" {
		return fmt.Sprintf("下注 %d", decision.BetSize)
	} else if strings.ToLower(decision.Action) == "raise" {
		return fmt.Sprintf("加注 %d", decision.BetSize)
	}
	return ""
}
func (h *TexasPokerDecisionHandler) newResp(ctx context.Context, result string) *ddbaby.TexasPokerDecisionResp {
	resp := &ddbaby.TexasPokerDecisionResp{
		Result: util.Ptr(result),
	}
	return resp
}

type TexasPokerDecisionV2 struct {
	Stage          string `json:"stage"`
	Action         string `json:"action"`
	BetSize        int32  `json:"bet_size"`
	HoleCards      string `json:"hole_cards"`
	CommunityCards string `json:"community_cards"`
}
