// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
	poker "github.com/kingjxu/ddbaby/dal/mysql/texas_poker"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"
)

// TexasPokerActive .
// @router /lyxz/gto_active [POST]
func TexasPokerActive(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.TexasPokerActiveReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := NewTexasPokerActiveHandler(&req).Handle(ctx)
	logrus.WithContext(ctx).Infof("[TexasPokerActive] resp:%v", util.ToJSON(resp))
	c.JSON(consts.StatusOK, resp)
}

type TexasPokerActiveHandler struct {
	req *ddbaby.TexasPokerActiveReq
}

func NewTexasPokerActiveHandler(req *ddbaby.TexasPokerActiveReq) *TexasPokerActiveHandler {
	return &TexasPokerActiveHandler{
		req: req,
	}
}

func (h *TexasPokerActiveHandler) check() error {
	if h.req.GetActiveCode() == "" { // 超过3秒，认为是过期
		return errors.New("activeCode is empty")
	}
	if h.req.GetUUID() == "" {
		return errors.New("uuid is empty")
	}
	return nil
}

func (h *TexasPokerActiveHandler) Handle(ctx context.Context) (*ddbaby.TexasPokerActiveResp, error) {
	logrus.WithContext(ctx).Infof("TexasPokerActiveHandler req:%v", util.ToJSON(h.req))
	err := h.check()
	if err != nil {
		logrus.WithContext(ctx).Errorf("check failed err:%v", err)
		return h.newResp(ctx, -1, err.Error()), err
	}
	info, err := poker.GetUserActiveCodeByCode(ctx, h.req.GetActiveCode())
	if err != nil {
		logrus.WithContext(ctx).Errorf("GetUserActiveCodeByCode failed err:%v", err)
		return h.newResp(ctx, -1, err.Error()), err
	}
	if info == nil || info.ActiveCode == "" {
		logrus.WithContext(ctx).Errorf("activeCode is invalid")
		return h.newResp(ctx, -1, "activeCode is invalid"), nil
	}
	if info.UserId != h.req.GetUUID() && info.UserId != "" {
		return h.newResp(ctx, -1, "active code has been used"), nil
	}
	info.UserId = h.req.GetUUID()
	err = poker.UpsertUserActiveCode(ctx, info)
	if err != nil {
		logrus.WithContext(ctx).Errorf("UpsertUserActiveCode failed err:%v", err)
		return h.newResp(ctx, -1, err.Error()), err
	}
	return h.newResp(ctx, 0, "success"), nil
}

func (h *TexasPokerActiveHandler) newResp(ctx context.Context, code int32, msg string) *ddbaby.TexasPokerActiveResp {
	resp := &ddbaby.TexasPokerActiveResp{
		BaseResp: &ddbaby.BaseResp{
			StatusCode:    code,
			StatusMessage: msg,
		},
	}
	return resp
}
