// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
	_const "github.com/kingjxu/ddbaby/const"
	"github.com/kingjxu/ddbaby/dal"
	"github.com/kingjxu/ddbaby/model"
	"github.com/kingjxu/ddbaby/service"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"
	"time"
)

// TexasPokerDecision .
// @router /lyxz/gto_decision [POST]
func TexasPokerDecision(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.TexasPokerDecisionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := NewTexasPokerDecisionHandler(&req).Handle(ctx)
	logrus.WithContext(ctx).Infof("[TexasPokerDecision] resp:%v", util.ToJSON(resp))
	c.JSON(consts.StatusOK, resp)
}

type TexasPokerDecisionHandler struct {
	req     *ddbaby.TexasPokerDecisionReq
	Action  string
	BetSize int32
}

func NewTexasPokerDecisionHandler(req *ddbaby.TexasPokerDecisionReq) *TexasPokerDecisionHandler {
	return &TexasPokerDecisionHandler{
		req: req,
	}
}

func (h *TexasPokerDecisionHandler) check() error {
	if len(h.req.GetImages()) == 0 {
		return errors.New("images is empty")
	}
	if time.Now().Unix()-h.req.GetTimestamp() > 100 { // 超过3秒，认为是过期
		return errors.New("timestamp is expired")
	}
	if h.req.GetUUID() == "" {
		return errors.New("uuid is empty")
	}
	return nil
}

func (h *TexasPokerDecisionHandler) Handle(ctx context.Context) (*ddbaby.TexasPokerDecisionResp, error) {
	logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] imagesLen:%v, timestamp:%v, uuid:%v, imageType:%v",
		len(h.req.GetImages()), time.Unix(h.req.GetTimestamp(), 0).Format(time.DateTime), h.req.GetUUID(), h.req.GetImageType())
	//1 数据校验
	var err error
	if err = h.check(); err != nil {
		logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] check err:%v", err)
		return h.newResp(ctx, "param err"), nil
	}
	//2 识别牌型
	images := h.req.GetImages()
	var recResult *model.TexasResult
	if h.req.GetImageType() == _const.ImageTypeUrl {
		recResult, err = service.RecognizePokerByFilePath(ctx, images[0])
		if err != nil {
			logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] service.RecognizePokerByFilePath err:%v", err)
			return h.newResp(ctx, "get decision err"), nil
		}
	} else {
		recResult, err = service.RecognizePoker(ctx, images[0])
		if err != nil {
			logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] service.RecognizePoker err:%v", err)
			return h.newResp(ctx, "get decision err"), nil
		}
	}
	logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] recognize poker:%v", util.ToJSON(recResult))
	//3 保存牌型
	if err = dal.SaveUserData(ctx, h.req.GetUUID(), recResult); err != nil {
		logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] saveUserData err:%v", err)
		return h.newResp(ctx, "save data err"), nil
	}
	//4 获取最新牌型
	latestData, err := dal.GetLastUserData(ctx, h.req.GetUUID())
	if err != nil {
		logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] GetLastUserData err:%v", err)
		return h.newResp(ctx, "get last data err"), nil
	}
	logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] latestData:%v", util.ToJSON(latestData))
	if !recResult.HeroInfo.IsHeroTurn {
		logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] not hero turn")
		return h.newResp(ctx, ""), nil
	}
	//5 决策
	resp, err := service.GtoDecision(ctx, model.Conv2TexasGtoDecisionReq(ctx, latestData))
	if err != nil {
		logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] GtoDecision err:%v", err)
		return h.newResp(ctx, "get err"), nil
	}
	logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] resp:%v", util.ToJSON(resp))
	return h.newResp(ctx, ""), nil
}

func (h *TexasPokerDecisionHandler) newResp(ctx context.Context, result string) *ddbaby.TexasPokerDecisionResp {
	resp := &ddbaby.TexasPokerDecisionResp{
		Result: util.Ptr(result),
	}
	return resp
}
