// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"
)

// TexasPokerReport .
// @router /lyxz/gto_debug_log [POST]
func TexasPokerReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.TexasPokerReportReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := NewTexasPokerReportHandler(&req).Handle(ctx)
	logrus.WithContext(ctx).Infof("[TexasPokerReport] resp:%v", util.ToJSON(resp))
	c.JSON(consts.StatusOK, resp)
}

type TexasPokerReportHandler struct {
	req *ddbaby.TexasPokerReportReq
}

func NewTexasPokerReportHandler(req *ddbaby.TexasPokerReportReq) *TexasPokerReportHandler {
	return &TexasPokerReportHandler{
		req: req,
	}
}

func (h *TexasPokerReportHandler) check() error {
	return nil
}

func (h *TexasPokerReportHandler) Handle(ctx context.Context) (*ddbaby.TexasPokerReportResp, error) {
	logger := logrus.WithContext(ctx).WithField("uuid", h.req.GetUUID())
	logger.Infof("TexasPokerReportHandler req:%v", util.ToJSON(h.req))

	logLine := fmt.Sprintf("[%s] uuid=%s trigger=%s device=%s log=%s\n",
		time.Now().Format("2006-01-02 15:04:05.000"),
		h.req.GetUUID(),
		h.req.GetTrigger(),
		h.req.GetDevice(),
		h.req.GetLog(),
	)

	logPath := filepath.Join(".", fmt.Sprintf("%s-app.log", time.Now().Format("20060102")))
	f, err := os.OpenFile(logPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		logger.Errorf("open app.log failed err:%v", err)
		return h.newResp(ctx, -1, err.Error()), nil
	}
	defer f.Close()

	if _, err := f.WriteString(logLine); err != nil {
		logger.Errorf("write app.log failed err:%v", err)
		return h.newResp(ctx, -1, err.Error()), nil
	}

	return h.newResp(ctx, 0, "success"), nil
}

func (h *TexasPokerReportHandler) newResp(ctx context.Context, code int32, msg string) *ddbaby.TexasPokerReportResp {
	resp := &ddbaby.TexasPokerReportResp{
		BaseResp: &ddbaby.BaseResp{
			StatusCode:    code,
			StatusMessage: msg,
		},
	}
	return resp
}
