// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"
	_const "github.com/kingjxu/ddbaby/const"
	"github.com/kingjxu/ddbaby/service"
	"github.com/sirupsen/logrus"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

// TexasPokerDecision .
// @router /lyxz/gto_decision [POST]
func TexasPokerDecision(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.TexasPokerDecisionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, _ := NewTexasPokerDecisionHandler(&req).Handle(ctx)
	c.JSON(consts.StatusOK, resp)
}

type TexasPokerDecisionHandler struct {
	req     *ddbaby.TexasPokerDecisionReq
	Action  string
	BetSize int32
}

func NewTexasPokerDecisionHandler(req *ddbaby.TexasPokerDecisionReq) *TexasPokerDecisionHandler {
	return &TexasPokerDecisionHandler{
		req: req,
	}
}

func (h *TexasPokerDecisionHandler) check() error {
	if len(h.req.GetImages()) == 0 {
		return errors.New("images is empty")
	}
	return nil
}

func (h *TexasPokerDecisionHandler) Handle(ctx context.Context) (*ddbaby.TexasPokerDecisionResp, error) {
	logrus.WithContext(ctx).Infof("[TexasPokerDecisionHandler] imagesLen:%v", len(h.req.GetImages()))
	if err := h.check(); err != nil {
		logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] check err:%v", err)
		return h.newResp(ctx, -1, "param err"), nil
	}
	images := h.req.GetImages()
	imageType := _const.ImageTypeUrl
	if len(images[0]) > 512 { // 图片的二进制数据
		imageIDs, err := service.UploadImagesV2(ctx, images)
		if err != nil {
			logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] service.UploadImage err:%v", err)
			return h.newResp(ctx, -2, "upload image err"), nil
		}
		//	imageType = _const.ImageTypeFileID
		images = imageIDs
	}

	action, betSize, err := service.GetTexasPokerDecisionV2(ctx, images, imageType)
	if err != nil {
		logrus.WithContext(ctx).Errorf("[TexasPokerDecisionHandler] service.GetTexasPokerDecision err:%v", err)
		return h.newResp(ctx, -2, "get decision err"), nil
	}
	h.Action = action
	h.BetSize = betSize
	return h.newResp(ctx, 0, ""), nil
}

func (h *TexasPokerDecisionHandler) newResp(ctx context.Context, code int32, msg string) *ddbaby.TexasPokerDecisionResp {
	resp := &ddbaby.TexasPokerDecisionResp{
		BaseResp: &ddbaby.BaseResp{
			StatusMessage: msg,
			StatusCode:    code,
		},
	}
	resp.Action = &h.Action
	resp.BetSize = &h.BetSize
	return resp
}
