// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/common/adaptor"
	"github.com/kingjxu/ddbaby/json_callback/wxbizjsonmsgcrypt"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"
	"io"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

const (
	token          = "yGliIGnJ70LjtiD"
	encodingAeskey = "ymkfk4JAJBRMbCL2MmOkIYwhwm5FqYwy5upwoEjGIUu"
	receiverId     = "ww7e6919f510223ec1" // 企业微信ID
)

// WechatCallbackMsg .
// @router /wechat/callback_msg [GET]
func WechatCallbackMsg(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.WechatCallbackMsgReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	httpReq, err := adaptor.GetCompatRequest(&c.Request)
	if err != nil {
		logrus.WithContext(ctx).Errorf("GetCompatRequest err:%v", err)
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	NewWechatCallbackMsgHandler(httpReq, &req).Handle(ctx)
	c.JSON(consts.StatusOK, "")
}

type WechatCallbackMsgHandler struct {
	httpReq *http.Request
	req     *ddbaby.WechatCallbackMsgReq
	resp    *http.Response
}

func NewWechatCallbackMsgHandler(httpReq *http.Request, req *ddbaby.WechatCallbackMsgReq) *WechatCallbackMsgHandler {
	return &WechatCallbackMsgHandler{
		req:     req,
		httpReq: httpReq,
	}
}

func (h *WechatCallbackMsgHandler) check() error {
	return nil
}
func (h *WechatCallbackMsgHandler) Handle(ctx context.Context) {
	req := h.req
	logrus.WithContext(ctx).Infof("WechatCallbackMsgHandler req:%v", util.ToJSON(req))
	body, err := io.ReadAll(h.httpReq.Body)
	if err != nil {
		logrus.WithContext(ctx).Errorf("ReadAll err:%v", err)
		return
	}
	logrus.WithContext(ctx).Infof("WechatCallbackMsgHandler body:%v", string(body))
	wxcpt := wxbizjsonmsgcrypt.NewWXBizMsgCrypt(token, encodingAeskey, receiverId, wxbizjsonmsgcrypt.JsonType)
	msg, cryptErr := wxcpt.DecryptMsg(req.GetMsgSignature(), req.GetTimestamp(), req.GetNonce(), body)
	if cryptErr != nil {
		logrus.WithContext(ctx).Errorf("DecryptMsg code:%v,msg:%v", cryptErr.ErrCode, cryptErr.ErrMsg)
		return
	}

	logrus.WithContext(ctx).Infof("WechatCallbackMsgHandler msg:%v", util.ToJSON(msg))
}
