// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/kingjxu/ddbaby/util"
	"github.com/sirupsen/logrus"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

// WechatAddCustomCallback .
// @router /wechat/add_custom [POST]
func WechatAddCustomCallback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.WechatAddCustomCallbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ddbaby.WechatAddCustomCallbackResp)
	logrus.WithContext(ctx).Infof("WechatAddCustomCallback resp:%v", util.ToJSON(resp))
	c.JSON(consts.StatusOK, resp)
}
