package jk

import (
	"context"
	"github.com/kingjxu/ddbaby/dal/mysql"
)

// Code generated by sql2gorm. DO NOT EDIT.

// 健康评估问题表
type JkQo struct {
	ID           uint64 `gorm:"column:id;primary_key;AUTO_INCREMENT"` // 自增id
	JkType string `gorm:"column:jk_type;NOT NULL"`        // 病种类型
	Question      string `gorm:"column:question"`                       // 问题
	Options      string `gorm:"column:options"`                       // 问题选项
}

func (*JkQo) TableName() string {
	return "js_qo"
}

func GetQuestionsByType(ctx context.Context, jkType string) ([]*JkQo, error) {
	var questions []*JkQo
	err := mysql.GetDB(ctx).Where("jk_type = ?", jkType).Find(&questions).Error
	return questions, err
}
