// Code generated by hertz generator.

package ddbaby

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dreamexplainMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _lyxzMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _namefortuneMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _picknameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _taluopredictMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthevaluatequestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthcreateorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _jkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getjkqolistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _jkcreateorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}
