// Code generated by hertz generator.

package ddbaby

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hellomethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dreamexplainMw() []app.HandlerFunc {
	// your code...
	return nil
}
