// Code generated by hertz generator.

package ddbaby

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/kingjxu/ddbaby/biz/handler/ddbaby/health"
	"github.com/kingjxu/ddbaby/biz/handler/ddbaby/lyxz"
	ddbaby "github.com/kingjxu/ddbaby/biz/model/ddbaby"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(ddbaby.HelloResp)

	c.JSON(consts.StatusOK, resp)
}

// DreamExplain .
// @router /hello [GET]
func DreamExplain(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.DreamExplainReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, _ := lyxz.NewDreamExplainHandler(&req).Handle(ctx)

	c.JSON(consts.StatusOK, resp)
}

// PickName .
// @router /lyxz/pick_name [GET]
func PickName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.PickNameReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := lyxz.NewPickNameHandler(&req).Handle(ctx)

	c.JSON(consts.StatusOK, resp)
}

// NameFortune .
// @router /lyxz/name_fortune [GET]
func NameFortune(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.NameFortuneReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := lyxz.NewNameFortuneHandler(&req).Handle(ctx)

	c.JSON(consts.StatusOK, resp)
}

// TaLuoPredict .
// @router /lyxz/taluo_predict [GET]
func TaLuoPredict(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.TaLuoPredictReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := lyxz.NewTaLuoPredictHandler(&req).Handle(ctx)

	c.JSON(consts.StatusOK, resp)
}

// HealthEvaluateQuestions .
// @router /health/questions [GET]
func HealthEvaluateQuestions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req ddbaby.HealthEvaluateQuestionsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, _ := health.NewHealthQuestionsHandler(&req).Handle(ctx)

	c.JSON(consts.StatusOK, resp)
}
